### ISSUE TITLE
Reason: TypeError: Cannot read property 'imports' of undefined

### ISSUE THREAD

**Issue by japhfortin** [benwinding/quill-image-rotate-module#2]
Hi great plugin. However, I'm getting this error when trying to integrate the plugin to my app.
`Reason: TypeError: Cannot read property 'imports' of undefined`
![image](https://user-images.githubusercontent.com/29589649/74717728-db278500-526b-11ea-96c7-24f1e87e37fc.png)

![image](https://user-images.githubusercontent.com/29589649/74717675-c21ed400-526b-11ea-958e-9362e132e969.png)

That points to Toolbar.js line #5 or
`const Parchment = window.Quill.imports.parchment;`

Hope you can help. Thanks..

**Comment by benwinding** [comment]
Hey Sorry for the later reply that seems like an issue with `Quill` itself. Try asking on stackoverflow.
